# Generated by Django 3.2.4 on 2022-01-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaze',
            old_name='gaze',
            new_name='gazePassword',
        ),
    ]
